### ISSUE TITLE
Netbox - IPAM plugin

### ISSUE THREAD

**Issue by ramonvanalteren** [unomaly/Unomaly-roadmap#25]
Digital Ocean's IPAM tool: netbox (https://github.com/digitalocean/netbox) is often used to manage ipaddress allocation. See 

The plugin integrates the data from IPAM into Unomaly so systems and groups can be sourced from IPAM

**Comment by andskli** [comment]
A rough draft of this is now available at https://github.com/unomaly/netbox2unomaly, it could definitely benefit from some additional love, though.
